### ISSUE TITLE
Erorr While Runing App

### ISSUE THREAD

**Issue by KamalBalah** [mazenrashed/Printooth#90]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kamalbalah.myapplication321, PID: 30465
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kamalbalah.myapplication321/com.mazenrashed.printooth.ui.ScanningActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3143)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3252)
        at android.app.ActivityThread.access$1000(ActivityThread.java:197)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6892)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.mazenrashed.printooth.ui.ScanningActivity.onCreate(ScanningActivity.kt:31)
        at android.app.Activity.performCreate(Activity.java:6557)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3252) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:197) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6892) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file "/data/app/com.kamalbalah.myapplication321-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.view.LayoutInflater.createView(LayoutInflater.java:578)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195) 
        at com.mazenrashed.printooth.ui.ScanningActivity.onCreate(ScanningActivity.kt:31) 
        at android.app.Activity.performCreate(Activity.java:6557) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3252) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:197) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6892) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
    	Suppressed: java.lang.ClassNotFoundException: androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 23 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
I/Process: Sending signal. PID: 30465 SIG: 9

**Comment by rustamsobirov** [comment]
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0' add your gradle
